### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DanilPorkchop15**
major bug fix

### CODE REVIEW

**Review by Eclips4 — APPROVED** [review]

**Comment by DmitryHudrich** [comment]
tests?

**Comment by DanilPorkchop15** [comment]
> tests?

image

10/10. everything is fine.

**Review by xbt573 — APPROVED** [review]
lgtm

**Review by DanilPorkchop15 — COMMENTED** [review]
unbelievable

**Review by madeinheaven91 — APPROVED** [review]
Monumental

**Review by vlinear0 — APPROVED** [review]

**Review by SancheSLozovoy — APPROVED** [review]

**Comment by SancheSLozovoy** [comment]
omg

**Pull request closed without merging**
